/* Generated By:JavaCC: Do not edit this line. Eg3TreeConstants.java Version 5.0 */
public interface Eg3TreeConstants
{
  public int JJTSTART = 0;
  public int JJTVOID = 1;
  public int JJTADD = 2;
  public int JJTMULT = 3;
  public int JJTMYID = 4;
  public int JJTINTEGER = 5;


  public String[] jjtNodeName = {
    "Start",
    "void",
    "Add",
    "Mult",
    "MyID",
    "Integer",
  };
}
/* JavaCC - OriginalChecksum=e4c3adaf848f3a28a350845ec723237a (do not edit this line) */
